runtime: nodejs18

env_variables:
  PORT: 3111
  DBPASSWORD: postgres
  USERNAME: postgres
  HOST: 34.34.14.93
  DBPORT: 5432
  DATABASE: norris
  JWT_SECRET_KEY_ACCESS: 'SIKRETKAMUFLADZICBOSANSKITAJNIAGENT'
  JWT_SECRET_KEY_REFRESH: 'SIKRETKAMUFLADZICBOSANSKITAJNIAGENTTTT'
  CHUCKSEMAIL: ChakijaNorrisVic@outlook.com
  CHUCKSPASS: SmijesniVic123!